# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200)),
                ('webmail', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
    ]
