# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0004_auto_20171114_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
