# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-14 22:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0006_auto_20171115_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proman.department'),
        ),
    ]
