# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0007_auto_20171115_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='descrip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='desig',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phn_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resid',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
