# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-15 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0008_auto_20171115_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('thesisTitle', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proman.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuingStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('degree', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proman.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('PI', models.CharField(blank=True, max_length=200)),
                ('FundingAgency', models.CharField(blank=True, max_length=200)),
                ('syear', models.IntegerField(blank=True, default=2017)),
                ('fyear', models.IntegerField(blank=True, default=2018)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proman.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('books', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proman.UserProfile')),
            ],
        ),
    ]
