# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-15 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0009_completedstudent_continuingstudents_projects_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
