# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-16 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0014_auto_20171116_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='year',
            new_name='startYear',
        ),
        migrations.AddField(
            model_name='course',
            name='endYear',
            field=models.IntegerField(default=2018),
        ),
        migrations.AddField(
            model_name='edu',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='endTime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='startTime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexp',
            name='endTime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workexp',
            name='firm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workexp',
            name='startTime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='edu',
            name='degree',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='edu',
            name='descrip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='descrip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='desig',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
