# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0019_auto_20171121_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-endYear']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-fyear']},
        ),
    ]
