# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0020_auto_20171121_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phn_no',
            field=models.IntegerField(null=True),
        ),
    ]
