# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proman', '0023_auto_20171122_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proman.UserProfile'),
        ),
    ]
